name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  pages:
    name: Documentation to GitHub Pages
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
